spring:
  datasource:
    url: jdbc:h2:mem:spgrdb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false